# Source2Target Databricks App

command: ["uvicorn", "backend.app:app", "--host", "0.0.0.0", "--port", "8080"]

# Optional: If you need environment variables
# env:
#   - name: NODE_ENV
#     value: production
